import React, { Suspense } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutConfig from "root/utils/LayoutConfig";
import Script from "next/script";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <head>
          <Script
            src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=bod3qzg0rt"
            strategy="afterInteractive"
          />
        </head>
      </head>
      <body className="relative w-screen overflow-x-clip overflow-y-clip">
        <div className="absolute flex flex-col w-screen h-screen overflow-hidden mt-[75px]">
          <Suspense>
            <LayoutConfig />
            {children}
          </Suspense>
          <div id="rentModal"></div>
        </div>
        <Header className="absolute mt-[30px]"></Header>
      </body>
    </html>
  );
}
